version: '3'
services:
    web:
        build: .
        container_name: miradio-web
        env_file:
            - ".env"
#        ports:
#            - "80:880"
#            - "443:8443"
        # depends_on:
        #     - mysqldb
#    myadmin:
#        image: phpmyadmin/phpmyadmin
        # container_name: miradio-phpmyadmin
#        ports:
#            - "8080:80"
    #     environment:
    #         - PMA_ARBITRARY=1
    #         - PMA_HOST=${MYSQL_HOST}
    #     restart: always
    #     depends_on:
    #         - mysqldb
    # mysqldb:
    #     image: mysql
    #     container_name: ${MYSQL_HOST}
    #     restart: always
    #     env_file:
    #         - ".env"
    #     environment:
            # - MYSQL_DATABASE=${MYSQL_DATABASE}
            # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            # - MYSQL_USER=${MYSQL_USER}
            # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#        ports:
#            - "8989:3306"
#        volumes:
#            - "./data/db/mysql:/var/lib/mysql"